services:
  # xfoil-server:
  #   build: Xfoil-Server
  #   volumes:
  #    - ./XFOIL-Server/:/app
  #   ports:
  #     - "5000:5000"
  xfoil-web:
    restart: always
    command: sh -c "npm run dev"
    container_name: xfoil-web
    volumes:
     - ./:/app
     - /app/node_modules
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "3000:3000"
      - "3010:3010"
